- name: Deploy node exporter
  hosts: node-exporter
  roles:
    - ansible-node-exporter
  tags:
    - node-exporter

- name: Deploy prometheus
  hosts: prometheus
  roles:
    - ansible-prometheus
  tags:
    - prometheus
    - monitoring

- name: Deploy mikrotik-exporter
  hosts: mikrotik-exporter
  roles:
    - ansible-mikrotik-exporter
  tags:
    - monitoring
    - mikrotik-exporter    

- name: Deploy blackbox-exporter
  hosts: blackbox-exporter 
  roles:
    - ansible-blackbox-exporter
  tags:
    - monitoring
    - blackbox-exporter
 
- name: Make and copy certs
  hosts: grafana
  tasks:
    - file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      loop:
        - "{{ cert_crt_path }}"
        - "{{ cert_key_path }}"
        - "{{ cert_csr_path }}"

    - openssl_privatekey:
        path: "{{ cert_key_path }}grafana.nmc.bubnovd.net.pem"
      delegate_to: localhost
    
    - openssl_csr:
        path: "{{ cert_csr_path }}grafana.nmc.bubnovd.net.csr"
        privatekey_path: "{{ cert_key_path }}grafana.nmc.bubnovd.net.pem"
        common_name: "grafana.nmc.bubnovd.net"
      delegate_to: localhost
    
    - openssl_certificate:
        path: "{{ cert_crt_path }}grafana.nmc.bubnovd.net.crt"
        privatekey_path: "{{ cert_key_path }}grafana.nmc.bubnovd.net.pem"
        csr_path: "{{ cert_csr_path }}grafana.nmc.bubnovd.net.csr"
        provider: selfsigned
      delegate_to: localhost

    - copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        #        owner: grafana
        #        group: grafana
        mode: '0666'
      loop:
        - { src: "{{ cert_crt_path }}grafana.nmc.bubnovd.net.crt", dst: "/tmp/grafana.nmc.bubnovd.net.crt" }
        - { src: "{{ cert_key_path }}grafana.nmc.bubnovd.net.pem", dst: "/tmp/grafana.nmc.bubnovd.net.pem" }
      become: true
  tags:
    - grafana
    - certs

- name: Deploy grafana
  hosts: grafana
  roles:
    - ansible-grafana
  tags:
    - grafana
    - monitoring

- name: Deploy alertmanager
  hosts: alertmanager
  roles:
    - ansible-alertmanager
  tags:
    - alertmanager
    - monitoring

      #- name: Deploy alertmanager telegram bot
      #  hosts: alertmanager-bot
      #  roles:
      #    - ansible-alertmanager-bot
      #  tags:
      #    - alertmanager-bot
      #    - monitoring 
      #
