prometheus_version: 2.17.2
prometheus_storage_retention: "100d"
prometheus_storage_retention_size: "20GB"
prometheus_web_listen_address: "localhost:9090"

prometheus_alertmanager_config:
  - scheme: http
    static_configs:
      - targets:
        - "127.0.0.1:9093"

prometheus_targets:
  node:
    - targets:
            #        "{{ groups['node-exporter'] | map('extract', hostvars, ['ansible_host']) | map('regex_replace', '$', ':9100') | list }}"
            - "127.0.0.1:9100"
      labels:
        env: prod
  icmp:
    - targets: "{{ icmp_targets }}"
      labels:
        env: prod
  http:
    - targets: 
      - "http://bubnovd.net"
      - "https://mikrotik-ninja.ru"
      labels:
        env: prod
  alertmanager:
     - targets:
       - "127.0.0.1:9093"
       labels:
         env: prod
  grafana:
     - targets:
       - "127.0.0.1:3000"
       labels:
         env: prod

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "127.0.0.1:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
        - "/etc/prometheus/file_sd/node.yml"
  - job_name: "icmp"
    scrape_interval: "10s"
    scrape_timeout: "2s"
    metrics_path: "/probe"
    params:
      module: [icmp_test]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
    file_sd_configs:
      - files:
        - "/etc/prometheus/file_sd/icmp.yml"
  - job_name: "http"
    metrics_path: "/probe"
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
    file_sd_configs:
      - files:
        - "/etc/prometheus/file_sd/http.yml"
  - job_name: "alertmanager"
    file_sd_configs:
      - files:
        - "/etc/prometheus/file_sd/alertmanager.yml"
  - job_name: "grafana"
    file_sd_configs:
      - files:
        - "/etc/prometheus/file_sd/grafana.yml"
  - job_name: "mikrotik"
    scrape_timeout: "60s"
    scrape_interval: "120s"
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "127.0.0.1:9436"
  - job_name: "loki"
    static_configs:
      - targets:
          - "127.0.0.1:3100"
