mikrotik_targets:
  - name: "10.3.0.1"
    address: "10.3.0.1"
    port: 8729
    user: "monitoring"
    password: "{{ vault_mikrotik_exporter_password }}"
  - name: "10.4.0.1"
    address: "10.4.0.1"
    port: 8729
    user: "monitoring"
    password: "{{ vault_mikrotik_exporter_password }}"
