---
# - name: Download mikrotik_exporter binary to local folder
#   become: false
#   get_url:
#     url: "https://github.com/devi1/mikrotik-exporter/raw/master/releases/mikrotik-exporter"
#     dest: "/tmp/mikrotik-exporter"
#     validate_certs: false
#   register: _download_binary
#   until: _download_binary is success
#   retries: 5
#   delay: 2
#   delegate_to: localhost
#   check_mode: false

- name: create mikrotik_exporter system group
  group:
    name: "{{ mikrotik_exporter_group }}"
    system: true
    state: present

- name: create mikrotik_exporter system user
  user:
    name: "{{ mikrotik_exporter_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ mikrotik_exporter_group }}"
    createhome: false

- name: Propagate mikrotik Exporter binaries
  become: true
  copy:
    src: "releases/mikrotik-exporter"
    dest: "/usr/local/bin/mikrotik_exporter"
    mode: 0755
  notify:
    - restart mikrotik exporter

- name: set permissions for executable file
  file:
    dest: "/usr/local/bin/mikrotik_exporter"
    state: file
    owner: "{{ mikrotik_exporter_user }}"
    group: "{{ mikrotik_exporter_group }}"
    mode: 0750

- name: Create configuration directory
  file:
    path: "/etc/mikrotik_exporter"
    state: directory
    owner: "{{ mikrotik_exporter_user }}"
    group: "{{ mikrotik_exporter_group }}"
    mode: 0750

- name: Allow incoming connection from localhost
  iptables:
    chain: INPUT
    protocol: tcp
    destination: "{{ mikrotik_exporter_listen_address }}"
    destination_port: "{{ mikrotik_exporter_listen_port }}"
    jump: ACCEPT

- name: Drop all incoming connection
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ mikrotik_exporter_listen_port }}"
    jump: DROP    
