- name: Deploy server certificate
  hosts: user_vpn_server
  roles:
    - routeros-certificates
  tags:
    - deploy_server_certs

- name: Deploy OVPN server
  hosts: user_vpn_server
  roles:
    - routeros-ovpn-server
  tags:
    - deploy_ovpn_server

- name: Deploy client certificates
  hosts: user_vpn_server
  vars:
    certificates: "{{ client_certs }}"
  roles:
    - routeros-certificates
  tags:
    - deploy_client_certs

- name: Deploy client certificates
  hosts: user_vpn_server
  vars:
    certificates:
    - ros_cert_name: RB01
      ros_cert_days_valid: 365
      ros_cert_key_size: 4096
      ros_cert_key_usage: "tls-client"
      ros_cert_CA_name: CA
      ros_cert_is_CA: false
    - ros_cert_name: RB02
      ros_cert_days_valid: 365
      ros_cert_key_size: 4096
      ros_cert_key_usage: "tls-client"
      ros_cert_CA_name: CA
      ros_cert_is_CA: false
  roles:
    - routeros-certificates
  tags:
    - deploy_client_certs
    - clients

## Чтобы создать клиентов сначала запускаем плэйбук с --tags=deploy_client_certs, потом с тегом clients
